[package]
name = "operationlist"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
panic = "unwind"
strip = "symbols"

[dependencies]
confy = "0.6.1"
ratatui = "0.29.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.217"
